Fixing cannot runserver from main (temporary)
PichapopRo/project-pantry pull request #155
Opened 2024-11-05 14:14 UTC by PichapopRo

## What I have done
- Fixing cannot runserver by removing queryset from view

2024-11-06 08:04 UTC, knilios submitted a review, later dismissed
The filter is unusable.

2024-11-06 08:04 UTC, knilios commented on webpage/views.py
I think try doing something like:
```py
from webpage.modules.filter_object import FilterParam
...
param = FilterParam(offset = 1, number = view_count)
...
if ingredient:
    param.add_ingredient(ingredient.name) # Right now, only ingredient has an add method.
if equipment:
    param.equipment.append(equipment.name) # For other attribute, use attribute.append(name)
```
This should fix the problem.

2024-11-06 08:06 UTC, knilios requested changes
The filter is unusable.

2024-11-06 08:06 UTC, knilios commented on webpage/views.py
Please refer to previous comments.

2024-11-06 08:49 UTC, PichapopRo commented on webpage/views.py
This is just a temporary fix that hasn't applied the filter yet I did those because you cannot runserver after the merge of the new filter

2024-11-06 08:51 UTC, PichapopRo commented on webpage/views.py
I will try

2024-11-07 04:38 UTC, knilios approved these changes
Ok, I guess.

2024-11-07 15:10 UTC, merged