Chef badge
PichapopRo/project-pantry pull request #156
Opened 2024-11-06 06:41 UTC by PichapopRo

## What I have done
- After the user got at least 10 approved recipes. User will rewarded with a chef badge next to their name on the recipe page.

![image](https://github.com/user-attachments/assets/19a2878d-29e7-4e18-8969-629f4630c8be)

2024-11-06 08:17 UTC, SariyaP requested changes
Change this
![image](https://github.com/user-attachments/assets/be003c1e-a74f-4b51-84c7-67ac084e5910)

2024-11-06 08:22 UTC, knilios requested changes

2024-11-06 08:22 UTC, knilios commented on webpage/apps.py
Please add docstring to the methods and classes.

2024-11-06 08:22 UTC, knilios commented on webpage/signals.py
Please remove the magic number '10'

2024-11-06 08:22 UTC, knilios commented on webpage/templates/recipes/recipe_list.html
WHAT DO YOU MEAN BY 'funny haha badge'??? PLEASE CHANGE IT.

2024-11-06 08:22 UTC, knilios commented on webpage/utils.py
Magic number '10'. Maybe this number should be set in the env file.

2024-11-06 08:22 UTC, knilios commented on webpage/views.py
Please take a lot at my comments in the pull request #155.

2024-11-06 08:52 UTC, PichapopRo commented on webpage/templates/recipes/recipe_list.html
why not? la

2024-11-06 14:40 UTC, knilios commented on webpage/templates/recipes/recipe_list.html
**no**

2024-11-08 17:16 UTC, knilios approved these changes

2024-11-09 10:40 UTC, SariyaP approved these changes

2024-11-09 10:40 UTC, merged