Model test
PichapopRo/project-pantry pull request #85
Opened 2024-10-21 15:56 UTC by PichapopRo

## What I have done.
- Create a test and separate file for each model class test.

2024-10-21 16:34 UTC, knilios requested changes
I only have one issue. If this is fixed, it will be ready to merge.

2024-10-21 16:34 UTC, knilios commented on webpage/tests/test_recipe.py
The test test_get_steps should have tested with more steps. I suggest creating more steps and then testing their order.

2024-10-22 12:46 UTC, PichapopRo commented
I added more step feel free to review

2024-10-22 15:36 UTC, knilios approved these changes
OK

2024-10-22 15:58 UTC, merged