Adding html to string conversion
PichapopRo/project-pantry pull request #92
Opened 2024-10-22 13:53 UTC by PichapopRo

## What I have added.
- Adding HTML conversion to fix the fetched description came in HTML format.

2024-10-22 15:34 UTC, knilios requested changes
Mostly an issue with docstring and type hint.

2024-10-22 15:34 UTC, knilios commented on webpage/modules/proxy.py
The queryset type hint is gone.

2024-10-22 15:34 UTC, knilios commented on webpage/modules/builder.py
The__strip_html method has no type hint and is an incomplete docstring.

2024-10-23 07:46 UTC, SariyaP approved these changes
Looks ok

2024-10-23 08:24 UTC, knilios approved these changes
OK

2024-10-23 08:25 UTC, merged